### ISSUE TITLE
Create service component

### ISSUE THREAD

**Issue by consolelancer** [consolelancer/portfolio-shala#1]
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603121756/portfolio-shala/Group_38_xzwbrw.png" width="100%" height="600px"/>

<h1>Create Service Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder of Service Component</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>

**Comment by har882** [comment]
I wanted to be assigned to this, may I?

**Comment by consolelancer** [comment]
okay sure @har882

**Comment by consolelancer** [comment]
Thankyou @har882
