### ISSUE TITLE
Pagination and footer

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#13]
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603282205/portfolio-shala/pagination_hwnrpu.png" width="100%" height="50px"/>
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603282205/portfolio-shala/profilefooter_xygqis.png" width="100%" height="50px"/>

<h1>Create Footer Box Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder of Footer Box Component Design</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Use Shadow style</p>
<p>x=-3; y=4; blur=20; spread=1</p>
<p>Width:980px</p>
<p>height:50px</p>
<p>Backgroundcolor = #252531</p>

<p>Text color = #DCDCDC opacity(100%) fontsize=16px</p>
<p>Text yellow color = #FEC02F opacity(100%) fontsize=16px</p>

**Comment by VasuShrivastava** [comment]
Hi @Vansh1067 can I work on this!

**Comment by consolelancer** [comment]
yes you can @VasuShrivastava

**Comment by VasuShrivastava** [comment]
Hi @consolelancer @Vansh1067 can you review this please.

**Comment by consolelancer** [comment]
thankyou @VasuShrivastava  for more issue visit www.consolelancer.com
