### ISSUE TITLE
Portfolio-card 

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#16]
<h4>Before Hover mouse</h4>
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603282207/portfolio-shala/portfolio-pic_bltibo.png" width="300px" height="400px"/>
<h4>After Hover mouse</h4>
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603282207/portfolio-shala/portfolio-card_gvlodx.png" width="300px" height="400px"/>

<h1>Create Footer Box Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Use Shadow style</p>
<p>x=-3; y=4; blur=20; spread=1</p>
<p>Width:300px</p>
<p>height:350px</p>
<p>Backgroundcolor = #252531</p>

<p>Title color = #DCDCDC opacity(100%) fontsize=20px</p>
<p>Description color = #DCDCDC opacity(100%) fontsize=16px</p>
<p>Link color = #FEC02F opacity(100%) fontsize=16px</p>

**Comment by pratskalive08** [comment]
Hi, can I work on it?

**Comment by consolelancer** [comment]
yes you can @pratskalive08

**Comment by consolelancer** [comment]
Thankyou @pratskalive08  for more visit www.consolelancer.com
