### ISSUE TITLE
Education Card work history

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#17]
<h4>Education Card</h4>
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603282205/portfolio-shala/education-cards_yevfy6.png" width="420px" height="660px"/>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Use Shadow style</p>
<p>x=-3; y=4; blur=20; spread=1</p>
<p>Width:420px</p>
<p>height:220px</p>
<p>Backgroundcolor = #252531</p>

<p>Title color = #DCDCDC opacity(100%) fontsize=20px</p>
<p>Description color = #DCDCDC opacity(100%) fontsize=16px</p>
<p>Link color = #FEC02F opacity(100%) fontsize=16px</p>
<h4>TimeBox</h4>
<p>background color #1E1E28  width:180px height=30px <p>
<p>Text color #DCDCDC opacity 50% <p>

<h4>history Card</h4>
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603282205/portfolio-shala/workhistpory-card_jx9g5n.png" width="420px" height="720px"/>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Use Shadow style</p>
<p>x=-3; y=4; blur=20; spread=1</p>
<p>Width:420px</p>
<p>height:380px</p>
<p>Backgroundcolor = #252531</p>

<p>Title color = #DCDCDC opacity(100%) fontsize=20px</p>
<p>Description color = #DCDCDC opacity(100%) fontsize=16px</p>
<p>Link color = #FEC02F opacity(100%) fontsize=16px</p>
<h4>TimeBox</h4>
<p>background color #1E1E28  width:180px height=30px <p>
<p>Text color #DCDCDC opacity 50% <p>

<h1>Create Footer Box Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

**Comment by spyderglitch** [comment]
Hi, Can I work on this?

**Comment by consolelancer** [comment]
yes you can @spyderglitch

**Comment by consolelancer** [comment]
Thank you @spyderglitch
