### ISSUE TITLE
Portfolio-Details Card

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#26]
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603535804/portfolio-shala/Group_61_x9ojih.png" width="980px" height="520px"/>

<h1>Create Portfolio-Details Card Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder of Portfolio-Details Card  Design</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Use Shadow style</p>
<p>x=-3; y=4; blur=20; spread=1</p>

<p>Width:980px</p>
<p>height:520px</p>
<p>Description , Stacks and Reference Text Heading fontSize=20px color=#F8F8F8</p>
<p>Description , Stacks and Reference Text Details fontSize=16px color=#DCDCDC</p>
<p>Backgroundcolor = #252531</p>
<p>Stack Badge</P>
<Backgroundcolor=#181812 width=120px height=40px Textcolor=#DCDCDC textfontSize=20px</p>

<p>icons width=40px height=40px</p>

**Comment by spyderglitch** [comment]
Hi, can I wonk on it ?

**Comment by consolelancer** [comment]
yes @spyderglitch

**Comment by consolelancer** [comment]
thankyou @spyderglitch
