### ISSUE TITLE
Blog Info card

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#28]
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603535804/portfolio-shala/Group_55_jd0o8m.png" width="980px" height="120px"/>

<h1>Create Blog Info card</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder of Blog Info card Design</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Use Shadow style</p>
<p>x=-3; y=4; blur=20; spread=1</p>

<p>Width:980px</p>
<p>height:120px</p>
<p>Text fontSize=18px color=#DCDCDC</p>

<p>Backgroundcolor = #252531</p>

**Comment by spyderglitch** [comment]
Hi, Can I work on it?

**Comment by consolelancer** [comment]
yes you can @spyderglitch

**Comment by consolelancer** [comment]
Thankyou @spyderglitch
