### ISSUE TITLE
Price plans Card

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#3]
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603197260/portfolio-shala/priceplans_t0elgs.png" width="100%" height="400px"/>

<h1>Create Service Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder of Price Plans Component</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Width:300px</p>
<p>height:380px</p>
<p>Backgroundcolor = #252531</p>
<p>Price color= #FEC02F</p>
<p>Text Active color =F8F8F8 opacity 100%</p>
<p>Text Active color =F8F8F8 opacity 50%</p>
<h4>Symbols</h4>
<p>✓</p>
<p>✘</p>
<p>₹</p>

**Comment by IsabellaDev** [comment]
Hi, can I work on this one?

**Comment by consolelancer** [comment]
yes you can @isabellaliu77

**Comment by consolelancer** [comment]
thankyou @isabellaliu77
