### ISSUE TITLE
Review Card Design

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#4]
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603197278/portfolio-shala/Review_kyvbpx.png" width="100%" height="300px"/>

<h1>Create Service Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder of Review Component</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Width:470px</p>
<p>height:270px</p>
<p>Backgroundcolor = #252531</p>
<p>Star color= #FEC02F</p>
<p>Text Name color =F8F8F8 opacity 100%</p>
<p>Text Review color =F8F8F8 opacity 80%</p>
<p>Text Template author color =F8F8F8 opacity 50%</p>

**Comment by har882** [comment]
Can I work on this?

**Comment by consolelancer** [comment]
yes you can @har882

**Comment by consolelancer** [comment]
thankyou @har882
