### ISSUE TITLE
Side view toggle

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#5]
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603197738/portfolio-shala/left_nnvai7.png" width="80px" height="512px"/>

<h1>Create Service Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder of Review Component</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>use Shadow style</p>
<p>x=-3; y=4; blur=20; spread=1</p>
<p>Width:80px</p>
<p>height:100vh</p>
<p>Backgroundcolor = #1E1E28</p>

<p>Text color =F8F8F8 fontsize=20px</p>
<p>Social icon color =FEC02F width=height=40px</p>
<p>social icon background color = #252531 width=80px height=320px</p>
<p>Menu icon width=30px and height=20pc</p>

**Comment by har882** [comment]
Can I work on this?

**Comment by consolelancer** [comment]
yes sure i will assign to you @har882
