### ISSUE TITLE
Cover card

### ISSUE THREAD

**Issue by Vansh1067** [consolelancer/portfolio-shala#6]
<img src="https://res.cloudinary.com/drzmzowtg/image/upload/v1603197461/portfolio-shala/coverpic_sxgn04.png" width="100%" height="320px"/>

<h1>Create Service Component</h1>
<h4>How to contribute</h4>

<ul>
<li><p>Fork the repo</p></li>
<li><p>Clone the repo</p></li>
<li><p>Create the folder of Cover card Component</p></li>
<li><p>Create html and Css file in that folder</p></li>
<li><p>commit your all changes</p></li>
<li><p>Create pull request</p></li>
<li><p>Wait for merge your pull request</p></li>
</ul>

<h3>Information</h3>
<p>Use Only HTML5 and CSS3</p>
<p>Width:980px</p>
<p>height:300px</p>
<p>BackgroundRectangle color= #181822 ;opacity 60% width :940px and height:200px</p>
<p><code> color= #FEC02F</p>
<p>Heading color =F8F8F8 opacity 100%</p>

**Comment by har882** [comment]
I wanted to be assigned to this, may I?

**Comment by consolelancer** [comment]
okay @har882
